### ISSUE TITLE
Blockbook explorer for Pivx 'pivx.flitswallet.app' is giving 502 Bad Gateway.

### ISSUE THREAD

**Issue by greatwolf** [decenomy/FLS#10]
I don't know if this is the right place to submit this issue but the blockbook explorer for Pivx at pivx.flitswallet.app is down. If this isn't the right place where do I post about this problem? Who is suppose to be maintaining it and more importantly how do I get in contact with them?

Thanks.

**Comment by choochatjumpathongcj** [comment]
USPSDHL5109262575

**Comment by pedro-at-decenomy** [comment]
that is related to the service not the coin's core wallet code
